# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Geolonia 公式ドキュメント
            image: /img/logo.png
        nav:
            - item_name: チュートリアル
              item_url: '/tutorial/'
            - item_name: Embed API
              item_url: '/embed-api/'
              - item_name: JavaScript API
              item_url: '/javascript-api/'
            - item_name: カスタムスタイル
              item_url: '/custom-style/'
            - item_name: GeoJSON 仕様
              item_url: '/geojson/'

    footer:
        content:
            logo:
                text: Geolonia 公式ドキュメント
                image:
            copyright: Copyright &copy; 2020. - Geolonia.com <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            - network_name: github
              profile_url: 'https://github.com/geolonia/docs.geolonia.com'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'Gemfile','Gemfile.lock','Rakefile','vendor' ]
permalink: /:title/
